# Site settings
title: SysGeeks
email: paul@sysgeeks.com
description: "SysGeeks - Don't take care of the systems, Do want you like build a better site.  Leave all the routine maintenance to SysGeeks."
baseurl: ""
url: "http://sysgeeks.com"

# Build settings
markdown: kramdown
permalink: pretty
